In [4]:
import numpy as np

In [5]:
a=np.arange(10000)

In [6]:
l=list(range(10000))

In [7]:
%timeit for _ in range(100): a2=a*2

1.38 ms ± 1.86 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [8]:
%timeit for _ in range(100): l2=l*2

13.4 ms ± 190 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


# creating ndarrays in numpy

In [9]:
data=[1,2,3,4,5]
a1=np.array(data)
a1

array([1, 2, 3, 4, 5])

In [10]:
type(a1)

numpy.ndarray

In [11]:
data= [[1.,2,3],[4,5,6],[7,8,9]]

In [12]:
a1=np.array(data)

In [13]:
a1

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [14]:
type(a1)

numpy.ndarray

In [15]:
a1.shape

(3, 3)

In [16]:
a1.dtype

dtype('float64')

In [17]:
a1.ndim

2

In [18]:
x=np.arange(10)

In [19]:
type(x)

numpy.ndarray

In [20]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [21]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
np.full((2,3),fill_value=5)

array([[5, 5, 5],
       [5, 5, 5]])

In [23]:
np.empty(5)

array([ 0.0000000e+000, -5.4325031e-311,  0.0000000e+000,  0.0000000e+000,
        0.0000000e+000])

In [24]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## data type in numpy

In [25]:
np.arange(5,dtype=np.int32)

array([0, 1, 2, 3, 4])

In [26]:
np.arange(5,dtype=np.float64)

array([0., 1., 2., 3., 4.])

In [27]:
a=np.array([1,2.5,3.5])
b=a.astype(np.int32)
b

array([1, 2, 3])

## arithmatic using numpy ndarray

In [28]:
a1=np.array([1,2,3,4,5])
a1+2

array([3, 4, 5, 6, 7])

In [29]:
a1

array([1, 2, 3, 4, 5])

In [30]:
a1+a1

array([ 2,  4,  6,  8, 10])

In [31]:
a1*2

array([ 2,  4,  6,  8, 10])

In [32]:
a2=a1*2
a2

array([ 2,  4,  6,  8, 10])

In [33]:
a2//2

array([1, 2, 3, 4, 5], dtype=int32)

In [34]:
a2-1

array([1, 3, 5, 7, 9])

In [35]:
a2/2

array([1., 2., 3., 4., 5.])

In [36]:
6//a1

array([6, 3, 2, 1, 1], dtype=int32)

In [37]:
a1**2

array([ 1,  4,  9, 16, 25], dtype=int32)

In [38]:
a2=np.array([2,1,3,4,5])

In [39]:
a1>a2

array([False,  True, False, False, False])

In [40]:
a1<a2

array([ True, False, False, False, False])

## indexing and slicing

In [41]:
a=np.arange(10)

In [42]:
a[5]

5

In [43]:
a[0]

0

In [44]:
a[1:4]

array([1, 2, 3])

In [45]:
a[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
a[::2]

array([0, 2, 4, 6, 8])

In [47]:
a2=np.arange(11)

In [48]:
a2[:3]=11

In [49]:
a2

array([11, 11, 11,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
a2[:]=22

In [51]:
a2

array([22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22])

In [52]:
a1=np.arange(10)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
c=a1.copy()

In [54]:
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
c[:3]=33

In [56]:
c

array([33, 33, 33,  3,  4,  5,  6,  7,  8,  9])

In [57]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
a=np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [59]:
a[0][3]

4

## reshaping and transposing

In [60]:
a=np.arange(16)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [61]:
a1=a.reshape((4,4))
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [62]:
b=np.arange(16)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [63]:
a1=b.reshape((4,4))

In [64]:
a1.T

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [65]:
np.dot(a1,a1.T)

array([[ 14,  38,  62,  86],
       [ 38, 126, 214, 302],
       [ 62, 214, 366, 518],
       [ 86, 302, 518, 734]])

In [66]:
a1.swapaxes(1,0)

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [67]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [68]:
a1.swapaxes(0,0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

## function for ndarrays

In [69]:
a=np.array([3,2,5,6,7,9,8])
a

array([3, 2, 5, 6, 7, 9, 8])

In [70]:
a.sort()
a

array([2, 3, 5, 6, 7, 8, 9])

In [71]:
np.square(a)

array([ 4,  9, 25, 36, 49, 64, 81], dtype=int32)

In [72]:
np.sqrt(a)

array([1.41421356, 1.73205081, 2.23606798, 2.44948974, 2.64575131,
       2.82842712, 3.        ])

In [73]:
np.abs([-1,-2,-3])

array([1, 2, 3])

In [74]:
a1=np.array([1,2,3,4])
a2=np.array([5,6,7,8])
np.add(a1,a2)

array([ 6,  8, 10, 12])

In [75]:
np.subtract(a2,a1)

array([4, 4, 4, 4])

In [76]:
np.maximum(a1,a2)

array([5, 6, 7, 8])

In [77]:
a3=np.array([1,9,9,4])
a4=np.array([5,6,7,8])

In [78]:
np.maximum(a3,a4)

array([5, 9, 9, 8])

In [79]:
np.minimum(a3,a4)

array([1, 6, 7, 4])

In [80]:
np.power(a1,a2)

array([    1,    64,  2187, 65536], dtype=int32)

In [81]:
a1

array([1, 2, 3, 4])

In [82]:
a2

array([5, 6, 7, 8])

In [83]:
a

array([2, 3, 5, 6, 7, 8, 9])

In [84]:
np.greater(a2,a1)

array([ True,  True,  True,  True])

In [85]:
a2>a1

array([ True,  True,  True,  True])

In [86]:
np.less(a3,a4)

array([ True, False, False,  True])

## Mathematics and statistics

In [87]:
a=np.array([1,2,3,4,5,6,7,8,9])

In [88]:
a.mean()

5.0

In [89]:
a.sum()

45

In [90]:
a.min()

1

In [91]:
a.max()

9

In [92]:
a.var()

6.666666666666667

In [93]:
a.std()

2.581988897471611

In [94]:
a.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)

In [95]:
a.cumprod()

array([     1,      2,      6,     24,    120,    720,   5040,  40320,
       362880], dtype=int32)

In [96]:
a=np.arange(25)
a=a.reshape((5,5))

In [97]:
a.mean(axis=1)

array([ 2.,  7., 12., 17., 22.])

In [98]:
a.mean(axis=0)

array([10., 11., 12., 13., 14.])

In [99]:
a1=np.array([[1,2,3],[4,5,6],[7,8,9]])
a2=np.array([[1,2,3],[4,5,6],[7,8,9]])
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [100]:
a1.dot(a2)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [101]:
np.dot(a1,a2)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [102]:
from numpy.linalg import det, inv, eig

In [103]:
a=np.arange(16).reshape((4,4))

In [104]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [105]:
det(a)

-2.9582283945787796e-30

In [106]:
inv(a)

array([[ 9.00719925e+14, -4.50359963e+14, -1.80143985e+15,
         1.35107989e+15],
       [-2.40191980e+15,  2.70215978e+15,  1.80143985e+15,
        -2.10167983e+15],
       [ 2.10167983e+15, -4.05323966e+15,  1.80143985e+15,
         1.50119988e+14],
       [-6.00479950e+14,  1.80143985e+15, -1.80143985e+15,
         6.00479950e+14]])

## End